import ExcelJS from "exceljs";
import { saveAs } from "file-saver";
import { getSettings } from "@/features/settings/settings.storage";
import { calculateMetrics, computeRemaining, computeStudentStatus, getPaymentHistory, getStudentSavedAt } from "@/features/students/students.storage";
import type { Student } from "@/types/student";

const NAVY = "0F172A";
const SLATE = "1E293B";
const LIGHT = "F1F5F9";
const BORDER = "CBD5E1";
const WHITE = "FFFFFF";
const CYAN = "38BDF8";

const center = (wrapText = false): Partial<ExcelJS.Alignment> => ({ vertical: "middle", horizontal: "center", wrapText });
const border = (): ExcelJS.Borders => ({ top: { style: "thin", color: { argb: `FF${BORDER}` } }, bottom: { style: "thin", color: { argb: `FF${BORDER}` } }, left: { style: "thin", color: { argb: `FF${BORDER}` } }, right: { style: "thin", color: { argb: `FF${BORDER}` } } });
function styleTitle(sheet: ExcelJS.Worksheet, title: string, columns: number) { const end = String.fromCharCode(64 + columns); sheet.mergeCells(`A1:${end}1`); const cell = sheet.getCell("A1"); cell.value = title; cell.font = { name: "Segoe UI", size: 16, bold: true, color: { argb: `FF${WHITE}` } }; cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: `FF${NAVY}` } }; cell.alignment = center(); sheet.getRow(1).height = 36; }
function styleSubtitle(sheet: ExcelJS.Worksheet, subtitle: string, columns: number) { const end = String.fromCharCode(64 + columns); sheet.mergeCells(`A2:${end}2`); const cell = sheet.getCell("A2"); cell.value = subtitle; cell.font = { name: "Segoe UI", size: 11, bold: true, color: { argb: `FF${CYAN}` } }; cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: `FF${SLATE}` } }; cell.alignment = center(); sheet.getRow(2).height = 25; }
function styleMeta(sheet: ExcelJS.Worksheet, text: string, columns: number) { const end = String.fromCharCode(64 + columns); sheet.mergeCells(`A3:${end}3`); const cell = sheet.getCell("A3"); cell.value = text; cell.font = { name: "Segoe UI", size: 9.5, italic: true, color: { argb: "FF475569" } }; cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF1F5F9" } }; cell.alignment = center(); sheet.getRow(3).height = 23; sheet.getRow(4).height = 10; }
function styleHeader(row: ExcelJS.Row) { row.height = 30; row.eachCell((cell) => { cell.font = { name: "Segoe UI", size: 10.5, bold: true, color: { argb: `FF${WHITE}` } }; cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: `FF${SLATE}` } }; cell.alignment = center(true); cell.border = border(); }); }
function styleDataRow(row: ExcelJS.Row, zebra: boolean, numericColumns: number[] = []) { row.height = 24; row.eachCell((cell, col) => { cell.font = { name: "Segoe UI", size: 10, color: { argb: `FF${NAVY}` } }; cell.alignment = center(false); cell.border = border(); if (zebra) cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF8FAFC" } }; if (numericColumns.includes(col)) cell.numFmt = "#,##0"; }); }
function styleFooter(row: ExcelJS.Row, numericColumns: number[]) { row.height = 28; row.eachCell((cell, col) => { cell.font = { name: "Segoe UI", size: 10.5, bold: true, color: { argb: `FF${NAVY}` } }; cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE2E8F0" } }; cell.alignment = center(false); cell.border = border(); if (numericColumns.includes(col)) cell.numFmt = "#,##0"; }); }
function addDirectorySheet(workbook: ExcelJS.Workbook, name: string, students: Student[], title: string, academyName: string, currencyLabel: string, session: string, admin: string) {
  const sheet = workbook.addWorksheet(name, { views: [{ state: "frozen", ySplit: 7, showGridLines: true }] });
  const columns = 14;
  styleTitle(sheet, `${academyName.toUpperCase()} - ${title}`, columns); styleSubtitle(sheet, "STUDENT DIRECTORY & FEE COLLECTION", columns); styleMeta(sheet, `Institution: ${academyName}  |  Admin: ${admin}  |  Session: ${session}  |  Total Students: ${students.length}`, columns);
  const metrics = calculateMetrics(students);
  sheet.mergeCells("A5:C5"); sheet.getCell("A5").value = `Total Billed: ${currencyLabel} ${metrics.totalBilledFees.toLocaleString()}`; sheet.mergeCells("D5:F5"); sheet.getCell("D5").value = `Total Collected: ${currencyLabel} ${metrics.totalFeesCollected.toLocaleString()}`; sheet.mergeCells("G5:I5"); sheet.getCell("G5").value = `Outstanding: ${currencyLabel} ${metrics.totalOutstandingFees.toLocaleString()}`; sheet.mergeCells("J5:N5"); sheet.getCell("J5").value = `Collection Rate: ${metrics.totalBilledFees ? ((metrics.totalFeesCollected / metrics.totalBilledFees) * 100).toFixed(1) : "0.0"}%`;
  ["A5", "D5", "G5", "J5"].forEach((ref) => { const c = sheet.getCell(ref); c.font = { name: "Segoe UI", size: 10, bold: true, color: { argb: `FF${NAVY}` } }; c.fill = { type: "pattern", pattern: "solid", fgColor: { argb: `FF${LIGHT}` } }; c.alignment = center(); c.border = border(); }); sheet.getRow(5).height = 28; sheet.getRow(6).height = 10;
  const headers = ["Sr. #", "Student ID", "Gender", "Shift", "Student Full Name", "Phone / WhatsApp", "Course / Class", "Date Joined", "Saved At", `Total Fees (${currencyLabel})`, `Amount Paid (${currencyLabel})`, `Remaining Balance (${currencyLabel})`, "Payment Status", "Remarks / Notes"]; const header = sheet.getRow(7); header.values = headers; styleHeader(header); sheet.autoFilter = { from: { row: 7, column: 1 }, to: { row: 7, column: columns } };
  students.forEach((student, index) => { const status = computeStudentStatus(student.totalFees, student.amountPaid); const row = sheet.addRow([index + 1, student.id, student.gender || "Unspecified", student.shift === "Morning" ? "Morning" : student.shift === "Evening" ? "Evening" : "Unspecified", student.name, student.phone || "—", student.course || "—", student.dateJoined || "—", getStudentSavedAt(student), student.totalFees, student.amountPaid, computeRemaining(student.totalFees, student.amountPaid), status, student.notes || "—"]); styleDataRow(row, index % 2 === 1, [10, 11, 12]); const statusCell = row.getCell(13); statusCell.font = { name: "Segoe UI", size: 9.5, bold: true, color: { argb: status === "Paid" ? "FF15803D" : status === "Partial" ? "FF1D4ED8" : "FFB45309" } }; statusCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: status === "Paid" ? "FFDCFCE7" : status === "Partial" ? "FFDBEAFE" : "FFFEF3C7" } }; });
  const footer = sheet.addRow(["TOTAL", `Students: ${students.length}`, "", "", "", "", "", "", "", metrics.totalBilledFees, metrics.totalFeesCollected, metrics.totalOutstandingFees, "", ""]); styleFooter(footer, [10, 11, 12]); sheet.columns = [{ width: 8 }, { width: 16 }, { width: 14 }, { width: 18 }, { width: 28 }, { width: 18 }, { width: 24 }, { width: 15 }, { width: 22 }, { width: 18 }, { width: 18 }, { width: 20 }, { width: 16 }, { width: 34 }]; return sheet;
}

export async function exportAcademyToExcel(students: Student[]) {
  const settings = getSettings(); const academyName = settings.academyName?.trim() || "Academy Hub"; const currencyLabel = settings.currencyLabel || "Rs"; const session = settings.academicSession || "—"; const admin = settings.adminDisplayName || "Admin";
  const workbook = new ExcelJS.Workbook(); workbook.creator = admin; workbook.created = new Date(); workbook.modified = new Date();
  addDirectorySheet(workbook, "Students Directory", students, "STUDENT DIRECTORY & FEE RECORDS", academyName, currencyLabel, session, admin);
  addDirectorySheet(workbook, "Morning Students", students.filter((s) => s.shift === "Morning"), "MORNING SHIFT • 8:00 AM–2:00 PM", academyName, currencyLabel, session, admin);
  addDirectorySheet(workbook, "Evening Students", students.filter((s) => s.shift === "Evening"), "EVENING SHIFT", academyName, currencyLabel, session, admin);
  addDirectorySheet(workbook, "Male Students", students.filter((s) => s.gender === "Male"), "MALE STUDENTS", academyName, currencyLabel, session, admin);
  addDirectorySheet(workbook, "Female Students", students.filter((s) => s.gender === "Female"), "FEMALE STUDENTS", academyName, currencyLabel, session, admin);
  const payments = workbook.addWorksheet("Payment History", { views: [{ state: "frozen", ySplit: 4, showGridLines: true }] }); styleTitle(payments, `${academyName.toUpperCase()} - PAYMENT HISTORY`, 11); styleSubtitle(payments, "ALL RECORDED FEE PAYMENTS", 11); styleMeta(payments, `Institution: ${academyName}  |  Admin: ${admin}  |  Session: ${session}`, 11);
  const paymentHeaders = ["Sr. #", "Payment ID", "Student ID", "Student Name", "Amount", "Payment Date", "Payment Time", "Previous Paid", "New Paid", "Remaining", "Recorded By"]; const ph = payments.getRow(4); ph.values = paymentHeaders; styleHeader(ph); const allPayments = students.flatMap((student) => getPaymentHistory(student)); allPayments.forEach((payment, index) => { const row = payments.addRow([index + 1, payment.id, payment.studentId, payment.studentName, payment.amount, payment.paymentDate, payment.paymentTime, payment.previousPaid, payment.newPaid, payment.newRemaining, payment.recordedBy]); styleDataRow(row, index % 2 === 1, [5, 8, 9, 10]); }); const paymentTotal = allPayments.reduce((sum, payment) => sum + Number(payment.amount || 0), 0); const pf = payments.addRow(["TOTAL", `Payments: ${allPayments.length}`, "", "", paymentTotal, "", "", "", "", "", ""]); styleFooter(pf, [5]); payments.autoFilter = { from: { row: 4, column: 1 }, to: { row: 4, column: 11 } }; payments.columns = [{ width: 8 }, { width: 25 }, { width: 16 }, { width: 28 }, { width: 18 }, { width: 16 }, { width: 14 }, { width: 18 }, { width: 18 }, { width: 18 }, { width: 20 }];
  const summary = workbook.addWorksheet("Fee Summary", { views: [{ showGridLines: true }] }); styleTitle(summary, `${academyName.toUpperCase()} - EXECUTIVE FEE SUMMARY`, 4); styleSubtitle(summary, "ACADEMY-WIDE FINANCIAL OVERVIEW", 4); styleMeta(summary, `Institution: ${academyName}  |  Admin: ${admin}  |  Session: ${session}`, 4); const metrics = calculateMetrics(students); const summaryRows = [["Metric / Indicator", "Value", "Unit / Context", "Remarks"], ["Total Enrolled Students", students.length, "Students", "Current directory"], ["Total Billed Fees", metrics.totalBilledFees, currencyLabel, "All students"], ["Total Fees Collected", metrics.totalFeesCollected, currencyLabel, "All recorded paid amounts"], ["Total Outstanding", metrics.totalOutstandingFees, currencyLabel, "Current remaining balance"], ["Fully Paid Students", metrics.paidStudents, "Students", "Payment status"], ["Partial Students", metrics.partialStudents, "Students", "Payment status"], ["Pending Students", metrics.pendingStudents, "Students", "Payment status"]]; summaryRows.forEach((values, index) => { const row = summary.addRow(values); if (index === 0) styleHeader(row); else styleDataRow(row, index % 2 === 0, [2]); }); summary.columns = [{ width: 28 }, { width: 20 }, { width: 20 }, { width: 32 }];
  const analytics = workbook.addWorksheet("Fee Analytics", { views: [{ showGridLines: true }] }); styleTitle(analytics, `${academyName.toUpperCase()} - FEE ANALYTICS`, 5); styleSubtitle(analytics, "STATUS, SHIFT & GENDER BREAKDOWN", 5); styleMeta(analytics, `Institution: ${academyName}  |  Admin: ${admin}  |  Session: ${session}`, 5); const ah = analytics.addRow(["Category", "Students", "Billed", "Collected", "Outstanding"]); styleHeader(ah); const groups: Array<[string, Student[]]> = [["All Students", students], ["Morning Shift (8 AM–2 PM)", students.filter((s) => s.shift === "Morning")], ["Evening Shift", students.filter((s) => s.shift === "Evening")], ["Male Students", students.filter((s) => s.gender === "Male")], ["Female Students", students.filter((s) => s.gender === "Female")]]; groups.forEach(([label, group], index) => { const m = calculateMetrics(group); const row = analytics.addRow([label, m.totalStudents, m.totalBilledFees, m.totalFeesCollected, m.totalOutstandingFees]); styleDataRow(row, index % 2 === 1, [2, 3, 4, 5]); }); analytics.columns = [{ width: 30 }, { width: 16 }, { width: 18 }, { width: 18 }, { width: 20 }];
  workbook.worksheets.forEach((sheet) => { sheet.eachRow((row) => row.eachCell((cell) => { cell.alignment = { ...(cell.alignment || {}), vertical: "middle", horizontal: "center" }; })); });
  const now = new Date().toISOString().split("T")[0]; const filename = `${academyName.replace(/[^a-zA-Z0-9_-]/g, "_")}_Student_Directory_${now}.xlsx`; const buffer = await workbook.xlsx.writeBuffer(); saveAs(new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }), filename);
}
