import { createFileRoute, Link, useNavigate, redirect } from "@tanstack/react-router";
import { ArrowLeft, CheckCircle2, PlusCircle, Save } from "lucide-react";
import { useEffect, useState } from "react";
import { AppShell } from "@/components/academy/app-shell";
import { can } from "@/features/auth/permissions";
import { isWorkspaceSectionEnabled } from "@/features/workspace/workspace.storage";
import { Button } from "@/components/ui/button";
import { getSettings } from "@/features/settings/settings.storage";
import { getShiftById, formatShiftTime, getShifts, type AcademyShift } from "@/features/shifts/shifts.storage";
import { addStudent, computeRemaining, computeStudentStatus, formatCurrency } from "@/features/students/students.storage";
import { speakAgentMessage } from "@/features/agent/agent-voice";

export const Route = createFileRoute("/_authenticated/add-student")({ beforeLoad: () => { if (!isWorkspaceSectionEnabled("addStudent") || !can("studentsSave")) throw redirect({ to: "/dashboard" }); }, head: () => ({ meta: [{ title: "Add Student — Academy Hub" }, { name: "description", content: "Enroll a new student in Academy Hub." }] }), component: AddStudentPage });
const inputClass = "mt-1 h-10 w-full rounded-lg border border-input bg-background px-3 text-sm text-foreground outline-none transition-colors placeholder:text-muted-foreground focus:border-cyan-500 focus:ring-2 focus:ring-cyan-500/20";

function AddStudentPage() {
  const navigate = useNavigate(); const [settings, setSettings] = useState(getSettings); const currencyLabel = settings.currencyLabel || "Rs";
  const [shifts, setShifts] = useState<AcademyShift[]>(getShifts());
  useEffect(() => { const settingsFn = () => setSettings(getSettings()); const shiftsFn = () => setShifts(getShifts()); window.addEventListener("academy-settings-updated", settingsFn); window.addEventListener("academy-shifts-updated", shiftsFn); return () => { window.removeEventListener("academy-settings-updated", settingsFn); window.removeEventListener("academy-shifts-updated", shiftsFn); }; }, []);
  const [studentId, setStudentId] = useState(""); const [name, setName] = useState(""); const [gender, setGender] = useState<"" | "Male" | "Female">(""); const [shift, setShift] = useState(""); const [shiftTime, setShiftTime] = useState(""); const [phone, setPhone] = useState(""); const [course, setCourse] = useState(""); const [dateJoined, setDateJoined] = useState(""); const [totalFees, setTotalFees] = useState(""); const [amountPaid, setAmountPaid] = useState(""); const [notes, setNotes] = useState(""); const [errorMessage, setErrorMessage] = useState(""); const [successMessage, setSuccessMessage] = useState(""); const [isSubmitting, setIsSubmitting] = useState(false);
  const numTotal = parseFloat(totalFees) || 0; const numPaid = parseFloat(amountPaid) || 0; const isOverpaid = numPaid > numTotal; const remaining = computeRemaining(numTotal, numPaid); const autoStatus = computeStudentStatus(numTotal, numPaid);
  function handleShiftChange(value: string) { setShift(value); const saved = getShiftById(value); setShiftTime(formatShiftTime(saved)); }
  function resetForm() { setStudentId(""); setName(""); setGender(""); setShift(""); setShiftTime(""); setPhone(""); setCourse(""); setDateJoined(""); setTotalFees(""); setAmountPaid(""); setNotes(""); setErrorMessage(""); }
  function handleSave(addAnother = false) {
    setErrorMessage(""); setSuccessMessage(""); if (!studentId.trim()) return setErrorMessage("Student ID is required. Please choose and enter a unique Student ID."); if (!name.trim()) return setErrorMessage("Student Full Name is required."); if (totalFees.trim() === "" || isNaN(numTotal) || numTotal < 0) return setErrorMessage("Please enter a valid non-negative Total Fees amount."); if (numPaid < 0) return setErrorMessage("Amount Paid cannot be negative."); if (numPaid > numTotal) return setErrorMessage(`Amount Paid (${formatCurrency(numPaid)}) cannot be greater than Total Fees (${formatCurrency(numTotal)}).`);
    setIsSubmitting(true); const result = addStudent({ id: studentId.trim(), name: name.trim(), gender: gender || undefined, shift: shift === "morning" ? "Morning" : shift === "evening" ? "Evening" : undefined, shiftTime: shiftTime || undefined, phone: phone.trim() || undefined, course: course.trim() || undefined, dateJoined: dateJoined.trim() || undefined, totalFees: numTotal, amountPaid: numPaid, notes: notes.trim() || undefined }); setIsSubmitting(false);
    if (!result.success) return setErrorMessage(result.error || "Failed to register student.");
    const spokenMessage = `Sir, student ${name.trim()} has been added successfully.`;
    speakAgentMessage(spokenMessage);
    if (addAnother) { setSuccessMessage(`Student ${name.trim()} (${studentId.trim()}) successfully saved!`); resetForm(); window.scrollTo({ top: 0, behavior: "smooth" }); } else navigate({ to: "/students" });
  }
  return <AppShell title="Add Student" subtitle="Enroll a new student and establish their tuition fee structure." showAddStudent={false}><div className="mx-auto max-w-2xl"><div className="mb-4"><Button variant="ghost" size="sm" asChild className="gap-1.5 text-xs text-muted-foreground hover:text-foreground"><Link to="/students"><ArrowLeft className="size-3.5" />Back to Students</Link></Button></div>{successMessage && <div className="mb-5 flex items-center gap-2.5 rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-4 text-sm text-emerald-400"><CheckCircle2 className="size-4" />{successMessage}</div>}{errorMessage && <div className="mb-5 rounded-lg border border-destructive/30 bg-destructive/10 p-4 text-sm font-medium text-destructive">{errorMessage}</div>}
  <form onSubmit={(e) => { e.preventDefault(); handleSave(false); }} className="rounded-xl border border-border bg-card p-6 shadow-sm">
    <h2 className="font-display text-sm font-semibold tracking-wide text-cyan-400 uppercase">Student Identification</h2>
    <div className="mt-4 space-y-4"><div><label className="flex h-5 items-center justify-between text-xs font-medium"><span>Student ID *</span><span className="text-[11px] text-muted-foreground">Manual entry</span></label><input required value={studentId} onChange={(e) => setStudentId(e.target.value)} placeholder="e.g. STD-2026-01" className={`${inputClass} font-mono`} /></div><div><label className="flex h-5 items-center text-xs font-medium">Student Full Name *</label><input required value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Abdullah Khan" className={inputClass} /></div>
      <div className="grid items-start gap-4 sm:grid-cols-3"><div><label className="flex h-5 items-center text-xs font-medium">Gender</label><select value={gender} onChange={(e) => setGender(e.target.value as "" | "Male" | "Female")} className={inputClass}><option value="">Select gender</option><option value="Male">Male</option><option value="Female">Female</option></select></div><div><label className="flex h-5 items-center justify-between text-xs font-medium"><span>Phone / WhatsApp</span><span className="text-[11px] text-muted-foreground">Optional</span></label><input value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="e.g. 0300-1234567" className={inputClass} /></div><div><label className="flex h-5 items-center justify-between text-xs font-medium"><span>Course / Class</span><span className="text-[11px] text-muted-foreground">Optional</span></label><input value={course} onChange={(e) => setCourse(e.target.value)} placeholder="e.g. Mathematics" className={inputClass} /></div></div>
      <div className="grid items-start gap-4 sm:grid-cols-2"><div><label className="flex h-5 items-center justify-between text-xs font-medium"><span>Shift</span><span className="text-[11px] text-muted-foreground">Optional</span></label><select value={shift} onChange={(e) => handleShiftChange(e.target.value)} className={inputClass}><option value="">Select shift</option>{shifts.filter((s) => s.active).map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div><label className="flex h-5 items-center justify-between text-xs font-medium"><span>Shift Time</span><span className="text-[11px] text-muted-foreground">Automatic • editable</span></label><input value={shiftTime} onChange={(e) => setShiftTime(e.target.value)} placeholder="Select a shift to fill its saved time" className={inputClass} /><p className="mt-1 text-[11px] text-muted-foreground">Selecting a saved shift fills its configured time automatically. You may edit it if needed.</p></div></div>
      <div><label className="flex h-5 items-center justify-between text-xs font-medium"><span>Date Joined</span><span className="text-[11px] text-muted-foreground">Optional</span></label><input type="date" value={dateJoined} onChange={(e) => setDateJoined(e.target.value)} className={`${inputClass} cursor-pointer`} /></div></div>
    <hr className="my-6 border-border" /><h2 className="font-display text-sm font-semibold tracking-wide text-cyan-400 uppercase">Tuition Fee Structure</h2><div className="mt-4 space-y-4"><div className="grid gap-4 sm:grid-cols-2"><div><label className="text-xs font-medium">Total Fees ({currencyLabel}) *</label><input required type="number" min="0" step="any" value={totalFees} onChange={(e) => setTotalFees(e.target.value)} placeholder="e.g. 25000" className={`${inputClass} font-mono`} /></div><div><label className="text-xs font-medium">Amount Paid at Enrollment ({currencyLabel})</label><input type="number" min="0" step="any" value={amountPaid} onChange={(e) => setAmountPaid(e.target.value)} placeholder="e.g. 5000" className={`${inputClass} font-mono ${isOverpaid ? "border-destructive" : ""}`} /></div></div><div className="grid grid-cols-2 gap-3 rounded-lg border border-border bg-muted/30 p-3.5 text-xs"><div><p className="text-muted-foreground">Calculated Remaining</p><p className="mt-1 font-mono text-sm font-bold">{formatCurrency(remaining)}</p></div><div><p className="text-muted-foreground">Automatic Payment Status</p><p className="mt-1 text-sm font-bold">{autoStatus}</p></div></div></div>
    <hr className="my-6 border-border" /><label className="flex items-center justify-between text-xs font-medium"><span>Notes &amp; Remarks</span><span className="text-[11px] text-muted-foreground">Optional</span></label><textarea rows={3} value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Installment notes, concessions, or remarks..." className="mt-1.5 w-full rounded-lg border border-input bg-background px-3 py-3 text-sm" />
    <div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><Button type="button" variant="outline" asChild><Link to="/students">Cancel</Link></Button><Button type="button" variant="secondary" disabled={isSubmitting} onClick={() => handleSave(true)}><PlusCircle className="mr-1.5 size-4" />Save &amp; Add Another</Button><Button type="submit" disabled={isSubmitting} className="bg-cyan-600 text-white hover:bg-cyan-500"><Save className="mr-1.5 size-4" />Save Student</Button></div>
  </form></div></AppShell>;
}
