/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAddStudentRouteImport } from './routes/_authenticated/add-student'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedMaleStudentsRouteImport } from './routes/_authenticated/male-students'
import { Route as AuthenticatedFemaleStudentsRouteImport } from './routes/_authenticated/female-students'
import { Route as AuthenticatedMorningStudentsRouteImport } from './routes/_authenticated/morning-students'
import { Route as AuthenticatedEveningStudentsRouteImport } from './routes/_authenticated/evening-students'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({ id: '/_authenticated', getParentRoute: () => rootRouteImport } as any)
const LoginRoute = LoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRouteImport } as any)
const AuthenticatedAddStudentRoute = AuthenticatedAddStudentRouteImport.update({ id: '/add-student', path: '/add-student', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({ id: '/students', path: '/students', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedMaleStudentsRoute = AuthenticatedMaleStudentsRouteImport.update({ id: '/male-students', path: '/male-students', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedFemaleStudentsRoute = AuthenticatedFemaleStudentsRouteImport.update({ id: '/female-students', path: '/female-students', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedMorningStudentsRoute = AuthenticatedMorningStudentsRouteImport.update({ id: '/morning-students', path: '/morning-students', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedEveningStudentsRoute = AuthenticatedEveningStudentsRouteImport.update({ id: '/evening-students', path: '/evening-students', getParentRoute: () => AuthenticatedRouteRoute } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/add-student': typeof AuthenticatedAddStudentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/male-students': typeof AuthenticatedMaleStudentsRoute
  '/female-students': typeof AuthenticatedFemaleStudentsRoute
  '/morning-students': typeof AuthenticatedMorningStudentsRoute
  '/evening-students': typeof AuthenticatedEveningStudentsRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/add-student': typeof AuthenticatedAddStudentRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/_authenticated/male-students': typeof AuthenticatedMaleStudentsRoute
  '/_authenticated/female-students': typeof AuthenticatedFemaleStudentsRoute
  '/_authenticated/morning-students': typeof AuthenticatedMorningStudentsRoute
  '/_authenticated/evening-students': typeof AuthenticatedEveningStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByTo
  id: keyof FileRoutesById
  fileRoutesById: FileRoutesById
}
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/_authenticated': { id: '/_authenticated'; path: ''; fullPath: '/'; preLoaderRoute: typeof AuthenticatedRouteRouteImport; parentRoute: typeof rootRouteImport }
    '/login': { id: '/login'; path: '/login'; fullPath: '/login'; preLoaderRoute: typeof LoginRouteImport; parentRoute: typeof rootRouteImport }
    '/_authenticated/add-student': { id: '/_authenticated/add-student'; path: '/add-student'; fullPath: '/add-student'; preLoaderRoute: typeof AuthenticatedAddStudentRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/dashboard': { id: '/_authenticated/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof AuthenticatedDashboardRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/settings': { id: '/_authenticated/settings'; path: '/settings'; fullPath: '/settings'; preLoaderRoute: typeof AuthenticatedSettingsRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/students': { id: '/_authenticated/students'; path: '/students'; fullPath: '/students'; preLoaderRoute: typeof AuthenticatedStudentsRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/male-students': { id: '/_authenticated/male-students'; path: '/male-students'; fullPath: '/male-students'; preLoaderRoute: typeof AuthenticatedMaleStudentsRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/female-students': { id: '/_authenticated/female-students'; path: '/female-students'; fullPath: '/female-students'; preLoaderRoute: typeof AuthenticatedFemaleStudentsRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/morning-students': { id: '/_authenticated/morning-students'; path: '/morning-students'; fullPath: '/morning-students'; preLoaderRoute: typeof AuthenticatedMorningStudentsRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
    '/_authenticated/evening-students': { id: '/_authenticated/evening-students'; path: '/evening-students'; fullPath: '/evening-students'; preLoaderRoute: typeof AuthenticatedEveningStudentsRouteImport; parentRoute: typeof AuthenticatedRouteRoute }
  }
}
interface AuthenticatedRouteRouteChildren {
  AuthenticatedAddStudentRoute: typeof AuthenticatedAddStudentRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedMaleStudentsRoute: typeof AuthenticatedMaleStudentsRoute
  AuthenticatedFemaleStudentsRoute: typeof AuthenticatedFemaleStudentsRoute
  AuthenticatedMorningStudentsRoute: typeof AuthenticatedMorningStudentsRoute
  AuthenticatedEveningStudentsRoute: typeof AuthenticatedEveningStudentsRoute
}
const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAddStudentRoute,
  AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute,
  AuthenticatedStudentsRoute,
  AuthenticatedMaleStudentsRoute,
  AuthenticatedFemaleStudentsRoute,
  AuthenticatedMorningStudentsRoute,
  AuthenticatedEveningStudentsRoute,
}
const AuthenticatedRouteRouteWithChildren = AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)
interface RootRouteChildren { IndexRoute: typeof IndexRoute; AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren; LoginRoute: typeof LoginRoute }
const rootRouteChildren: RootRouteChildren = { IndexRoute, AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren, LoginRoute }
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' { interface Register { ssr: true; router: Awaited<ReturnType<typeof getRouter>>; config: Awaited<ReturnType<typeof startInstance.getOptions>> } }
